### ISSUE TITLE
localhost internet access

### ISSUE THREAD

**Issue by wiksito** [dobladov/koreader-node-sync-server#1]
Hi, is there anyway to access sync server from the internet? I've tried port forwarding but it doesn't work.

Thanks

**Comment by dobladov** [comment]
Honestly I have not used this repository for a long time and I can't guarantee that it still woks, I was thinking to archive the repo.

If you want to try, make sure that your server host is correct and you can reach the server with your local IP address.

```
SERVER_HOST=0.0.0.0
```

**Comment by wiksito** [comment]
> Honestly I have not used this repository for a long time and I can't guarantee that it still woks, I was thinking to archive the repo.
> 
> If you want to try, make sure that your server host is correct and you can reach the server with your local IP address.
> 
> ```
> SERVER_HOST=0.0.0.0
> ```
@dobladov, hi, I actually got it to work on LAN but just trying to connect to it from the internet.

Thanks!

**Comment by Jbbrack03** [comment]
> > Honestly I have not used this repository for a long time and I can't guarantee that it still woks, I was thinking to archive the repo.
> > If you want to try, make sure that your server host is correct and you can reach the server with your local IP address.
> > ```
> > SERVER_HOST=0.0.0.0
> > ```
> 
> @dobladov, hi, I actually got it to work on LAN but just trying to connect to it from the internet.
> 
> Thanks!

There's something going on with your server/network. I just set it up on an Ubuntu 20.04 headless server and I can sync outside of my LAN. In the sync server config, I entered the private IP for my Ubuntu Server. And then I created a DHCP reservation for that IP in my router and then forwarded port 3000 to it. Working perfectly!

Oh, and I hope that the developer doesn't archive this. It's the best Self-Hosted sync plugin available right now.

**Comment by dobladov** [comment]
@wiksito I made https optional since it might be causing your problem, please try again without using the certificates like is shown in the [Readme](https://github.com/dobladov/koreader-node-sync-server/blob/master/README.md).

To make sure that the server can be reachable from the internet you can try a localtunnel.

```bash
npx localtunnel -h "http://serverless.social" -p 3000
```
Once is running try to access the generated URL like this: http://little-kangaroo-53.serverless.social/healthcheck

If you can reach the server this way it means that your configuration for port forwarding must be wrong.

**Comment by wiksito** [comment]
@Jbbrack03 Thanks for the assurance that it works. I actually did all that but no luck. I'm on Win10 so don't know if that makes a difference.

@dobladov I think you're right that it might has something to do with https. I can connect through internet using your instruction above with localtunnel. But not when I use https. I have Asus Router and pretty sure I forward the properly . I even tried to disable my network firewall, nothing works with https:.

I should have posted this earlier but this is what I get when I try to use my WAN IP in .env. If I leave the host as localhost or 0.0.0.0, my WAN IP wouldn't work even if the port is forwarded to the localhost machine.

`D:\koreader-node-sync-server-master>npm start

> koreader@1.0.3 start D:\koreader-node-sync-server-master
> node src/index

events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL: address not available xxx.xxx.xxx.xxx:3000
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at doListen (net.js:1500:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'xxx.xxx.xxx.xxx',
  port: 3000
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! koreader@1.0.3 start: `node src/index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the koreader@1.0.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Server\AppData\Roaming\npm-cache\_logs\2020-05-16T20_17_44_417Z-debug.log
`

Thanks and, yes, please do not archive this.

**Comment by dobladov** [comment]
@wiksito for .env I would use the local ip of the machine running the server, something like `192.168.1.x`.

Then in your router settings you should open the port pointing to that local IP.

![image](https://user-images.githubusercontent.com/1938043/82140955-deaeb600-9832-11ea-8bc6-74ff457f9e84.png)

I don't think your WAN IP is required for anything else than to access the server from the internet.

Make sure the server us updated with `git pull` and `CERTIFICATES_FOLDER = './certificates'` is not present on your `.env`

If this does not work, I'm sorry to say that I'm out of ideas.
